base:
  random_state: 42

data_load:
  dataset_path: data/raw/insurance_data.csv

featurize:
  processed_path: data/processed/featured_insurance_data.csv
  categorical_features: ["gender", "smoker", "region"]
  numerical_features: ["age", "bmi", "children"]
  target_column: "charges"

data_split:
  test_size: 0.2
  trainset_path: data/processed/train_insurance.csv
  testset_path: data/processed/test_insurance.csv

train:
  model_path: models/model.joblib
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42

evaluate:
  metrics_path: reports/metrics.json
  drift_report_path: reports/data_drift.html
  system_metrics_path: reports/system_metrics.json
